name: Deploy Azure Function

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3

    - name: Log in to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Install Az modules
      run: |
        Install-Module -Name Az -Force -Scope CurrentUser

    - name: List SQL Servers and Databases
      shell: pwsh
      run: |
        Get-AzSubscription
        Get-AzResourceGroup
        Get-AzSqlServer
